testing:
  image: ${CI_REGISTRY}/developers/docker-images:git
  stage: test
  environment:
    name: Testing
    url: http://dsbn-slate.testphp.dsbn.org
  tags:
    - linux
  script:
    - rm -rf .git
    - git init
    - git add -f .static ./dist
    - git commit -m "Project:${CI_PROJECT_URL}\nSHA:${CI_COMMIT_SHA}"
    - git push -f dokku@edcphptest:"$CI_PROJECT_NAME" HEAD:refs/heads/master

internal:
  image: ${CI_REGISTRY}/developers/docker-images:git
  stage: deploy
  environment:
    name: Production
    url: http://dsbn-slate.intdokku.dsbn.org
  tags:
    - linux
  when: manual
  only: 
    - master
  script:
    - rm -rf .git
    - git init
    - git add -f .static ./dist
    - git commit -m "Project:${CI_PROJECT_URL}\nSHA:${CI_COMMIT_SHA}"
    - git push -f dokku@edcintdokku:"$CI_PROJECT_NAME" HEAD:refs/heads/master
